const { createGestureStore } = require('../../services/gesture-store');
const { classifyFinger } = require('../../services/gesture-matcher');
const { roundForUi } = require('../../utils/realtime-view');
const labels = ['左拇指', '左食指', '左中指', '左无名指', '左小指', '右拇指', '右食指', '右中指', '右无名指', '右小指'];
function item(value, index, enabled) { if (!enabled) return { label: labels[index], value: 0, state: '已关闭', tone: 'idle', disabled: true }; const state = classifyFinger(value); const tone = state === 'straight' ? 'success' : state === 'half' ? 'warning' : state === 'full' ? 'danger' : 'idle'; return { label: labels[index], value: Number.isFinite(value) ? roundForUi(value) : 0, state: state === 'straight' ? '平直' : state === 'half' ? '半弯' : state === 'full' ? '全弯' : '等待', tone, disabled: false }; }
Page({
  data: { connected: false, statusTone: 'idle', statusText: '请先连接设备并做出要保存的动作。', fingers: [], pose: { roll: '--', pitch: '--', yaw: '--' }, name: '', action: '', categoryIndex: 0, categoryOptions: ['翻译文本', '训练目标', '控制动作'] },
  onLoad() { this.runtime = getApp().getRuntime(); this.store = createGestureStore(); this.active = true; this.unsubscribe = this.runtime.subscribe((state) => this.applyState(state)); },
  onShow() { this.active = true; this.applyState(this.runtime.getState()); }, onHide() { this.active = false; }, onUnload() { if (this.unsubscribe) this.unsubscribe(); },
  applyState(state) { if (!this.active) return; const enabledFingers = state.calibration.enabledFingers; const valid = enabledFingers.some(Boolean) && state.flex.every((value, index) => enabledFingers[index] === false || typeof value === 'number'); this.setData({ connected: state.connected, statusTone: state.connected ? 'success' : state.connecting ? 'warning' : 'idle', statusText: valid ? '当前已启用手指的数据已就绪，可以捕获此刻姿态。' : enabledFingers.some(Boolean) ? state.statusText : '请先到设备状态页启用至少一根手指。', fingers: state.flex.map((value, index) => item(value, index, enabledFingers[index] !== false)), pose: { roll: typeof state.pose.roll === 'number' ? state.pose.roll.toFixed(1) : '--', pitch: typeof state.pose.pitch === 'number' ? state.pose.pitch.toFixed(1) : '--', yaw: typeof state.pose.yaw === 'number' ? state.pose.yaw.toFixed(1) : '--' } }); },
  changeName(e) { this.setData({ name: e.detail.value }); }, changeAction(e) { this.setData({ action: e.detail.value }); }, changeCategory(e) { this.setData({ categoryIndex: Number(e.detail.value) }); },
  save() { const state = this.runtime.getState(); const enabledFingers = state.calibration.enabledFingers; if (!enabledFingers.some(Boolean)) { wx.showToast({ title: '请先启用至少一根手指', icon: 'none' }); return; } if (!state.flex.every((value, index) => enabledFingers[index] === false || typeof value === 'number')) { wx.showToast({ title: '等待已启用手指的数据后再保存', icon: 'none' }); return; } if (!this.data.name.trim() || !this.data.action.trim()) { wx.showToast({ title: '请填写手势名称和文字含义', icon: 'none' }); return; } const category = ['translation', 'training', 'control'][this.data.categoryIndex]; this.store.add({ name: this.data.name, action: this.data.action, category, fingers: state.flex, states: state.fingerStates, pose: state.pose, matchPose: false, poseTolerance: 8 }); wx.showToast({ title: '手势已保存', icon: 'success' }); setTimeout(() => wx.navigateTo({ url: '/pages/gesture-library/gesture-library' }), 500); }
});
