[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
upload_speed = 57600
upload_resetmethod = ck
board_build.flash_mode = dout
board_build.f_cpu = 80000000L
lib_deps =
  knolleary/PubSubClient @ ^2.8
  tzapu/WiFiManager @ ^2.0.17
